const SITE='https://mengjingyi81-ux.github.io/yunying-mianshi-trainer/';
export default {
 async fetch(req,env){if(req.method!=='POST')return new Response('运营面试飞书机器人运行中');const body=await req.json();if(body.challenge)return Response.json({challenge:body.challenge});if(body.header?.event_type!=='im.message.receive_v1')return Response.json({ok:true});const text=JSON.parse(body.event.message.content||'{}').text?.trim();if(!text)return Response.json({ok:true});await handleAnswer(text,env);return Response.json({ok:true})},
 async scheduled(event,env){const now=new Date(Date.now()+8*3600*1000),day=now.getUTCDay();if(day===0&&now.getUTCHours()>=20)await sendWeekly(env);else await startDaily(env)}
};
async function token(env){const r=await fetch('https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({app_id:env.FEISHU_APP_ID,app_secret:env.FEISHU_APP_SECRET})}),j=await r.json();if(!j.tenant_access_token)throw Error(j.msg||'Feishu auth failed');return j.tenant_access_token}
async function send(text,env){const t=await token(env),type=env.FEISHU_RECEIVE_ID_TYPE||'open_id',r=await fetch('https://open.feishu.cn/open-apis/im/v1/messages?receive_id_type='+type,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify({receive_id:env.FEISHU_RECEIVER_ID,msg_type:'text',content:JSON.stringify({text})})});if(!r.ok)throw Error('Feishu send failed: '+await r.text())}
async function bank(){return fetch(SITE+'questions.json').then(r=>r.json())}
async function startDaily(env){const qs=(await bank()).sort(()=>Math.random()-.5).slice(0,3),state={date:new Date().toISOString().slice(0,10),index:0,qs,records:[],startedAt:Date.now()};await env.TRAINING_STATE.put('current',JSON.stringify(state));await send('📘 今日运营面试训练 · 第1/3题\n\n题型：'+qs[0].cat+'\n场景：'+qs[0].scene+'\n题目：'+qs[0].q+'\n\n直接回复你的回答即可，我会继续评价。',env)}
async function handleAnswer(answer,env){const raw=await env.TRAINING_STATE.get('current');if(!raw){await send('今天的训练尚未开始。发送“开始训练”可立即开始。',env);if(/开始/.test(answer))await startDaily(env);return}const s=JSON.parse(raw),q=s.qs[s.index],record=await evaluate(q,answer,env);record.date=new Date().toISOString();record.duration=Math.round((Date.now()-s.startedAt)/1000);s.records.push(record);let feedback='✅ 第'+(s.index+1)+'题评价：'+record.score+'分\n\n主要卡点：'+record.mainGap+'\n\n改进建议：'+record.advice+'\n\n面试版回答：\n'+record.interviewAnswer;if(s.index<2){s.index++;s.startedAt=Date.now();await env.TRAINING_STATE.put('current',JSON.stringify(s));const n=s.qs[s.index];await send(feedback+'\n\n——\n📘 第'+(s.index+1)+'/3题\n题型：'+n.cat+'\n题目：'+n.q,env)}else{await saveHistory(s,env);await env.TRAINING_STATE.delete('current');await send(feedback+'\n\n'+dailyReport(s),env)}}
async function evaluate(q,answer,env){if(!env.OPENAI_API_KEY)return localEval(q,answer);const prompt='你是资深互联网运营面试官。按问题理解20、分析框架25、运营经验20、数据意识20、表达结构15评分。返回纯JSON：score,dimensions,gaps,mainGap,advice,interviewAnswer。题目：'+q.q+'；参考框架：'+q.formula+'；回答：'+answer;try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+env.OPENAI_API_KEY},body:JSON.stringify({model:env.OPENAI_MODEL||'gpt-5-mini',input:prompt})}),j=await r.json();return {...JSON.parse(j.output_text.replace(/^\x60\x60\x60json|\x60\x60\x60$/g,'').trim()),q:q.q,cat:q.cat,answer,knowledge:q.knowledge}}catch{return localEval(q,answer)}}
function localEval(q,a){const signals=['目标','指标','分层','原因','策略','数据','验证','实验','风险','复盘'],hits=signals.filter(x=>a.includes(x)).length,score=Math.min(92,Math.max(40,40+hits*4+Math.round(Math.min(a.length,300)/15))),gap=!a.includes('指标')?'缺少指标体系和效果验证':!a.includes('分层')?'没有按用户或场景进行分层':'案例细节与量化结果不足';return {q:q.q,cat:q.cat,answer:a,score,dimensions:{understanding:Math.round(score*.2),framework:Math.round(score*.25),experience:Math.round(score*.2),data:Math.round(score*.2),expression:Math.round(score*.15)},gaps:[gap],mainGap:gap,advice:'按“'+q.formula+'”重组答案，并补充一个量化结果。',interviewAnswer:'我会先明确目标和数据口径，再按“'+q.formula+'”定位关键环节；随后提出有优先级的策略，用小流量实验验证增量，并设置成本与体验护栏。',knowledge:q.knowledge}}
function dailyReport(s){const scores=s.records.map(r=>r.score),avg=Math.round(scores.reduce((a,b)=>a+b,0)/scores.length),gaps=s.records.map(r=>r.mainGap);return '📊 今日训练日报\n训练题数：3\n平均分：'+avg+'\n最高：'+Math.max(...scores)+'\n最低：'+Math.min(...scores)+'\n\n当前问题：'+[...new Set(gaps)].join('；')+'\n下一步：优先复练本轮最低分题目，并补足指标、案例与验证闭环。'}
async function saveHistory(s,env){const now=new Date(Date.now()+8*3600*1000),key='week:'+weekKey(now),old=JSON.parse(await env.TRAINING_STATE.get(key)||'[]');old.push({date:s.date,records:s.records});await env.TRAINING_STATE.put(key,JSON.stringify(old))}
function weekKey(d){const one=new Date(Date.UTC(d.getUTCFullYear(),0,1)),days=Math.floor((d-one)/86400000);return d.getUTCFullYear()+'-'+String(Math.ceil((days+one.getUTCDay()+1)/7)).padStart(2,'0')}
async function sendWeekly(env){const now=new Date(Date.now()+8*3600*1000),items=JSON.parse(await env.TRAINING_STATE.get('week:'+weekKey(now))||'[]'),rs=items.flatMap(x=>x.records||[]);if(!rs.length)return send('📅 本周暂无完整训练记录。下周继续保持每天3题。',env);const avg=Math.round(rs.reduce((s,r)=>s+r.score,0)/rs.length),gaps=[...new Set(rs.map(r=>r.mainGap))].slice(0,4),knowledge=[...new Set(rs.flatMap(r=>r.knowledge||[]))].slice(0,6);let detail=rs.map((r,i)=>'\n'+(i+1)+'. '+r.q+'（'+r.score+'分）\n你的回答：'+r.answer+'\nAI优化：'+r.interviewAnswer).join('\n');await send('📅 运营面试训练周报\n本周完成：'+rs.length+'题\n平均分：'+avg+'\n\n主要问题：'+gaps.join('；')+'\n加强方向：指标拆解、真实案例、实验验证\n推荐知识：'+knowledge.join('、')+'\n\n题目与回答汇总：'+detail,env)}